PRODUCT_VERSION_MAJOR = 13
PRODUCT_VERSION_MINOR = 0
RISE_CODE := 3.0

RICE_FLAVOR := Tiramisu
RICE_VERSION := 8.0
RICE_CODENAME := Lomi
RICE_CODE := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)

ifeq ($(RICE_OFFICIAL), true)
    RICE_BUILDTYPE := OFFICIAL
else
    RICE_BUILDTYPE := COMMUNITY
endif

ifeq ($(WITH_GMS), true)
    ifeq ($(TARGET_CORE_GMS), true)
       RICE_PACKAGE_TYPE ?= CORE
    else ifeq ($(TARGET_OPTOUT_GOOGLE_TELEPHONY), true)
       RICE_PACKAGE_TYPE ?= GMS
    else
       RICE_PACKAGE_TYPE ?= PIXEL
    endif
else
       RICE_PACKAGE_TYPE ?= AOSP
endif

# Internal version
LINEAGE_VERSION := riceDroid-$(RICE_CODE)-$(shell date +%Y%m%d)-$(LINEAGE_BUILD)-v$(RICE_VERSION)-$(RICE_PACKAGE_TYPE)-$(RICE_BUILDTYPE)

# Display version
LINEAGE_DISPLAY_VERSION := riceDroid-$(RICE_CODE)-$(LINEAGE_BUILD)-v$(RICE_VERSION)-$(RICE_PACKAGE_TYPE)-$(RICE_BUILDTYPE)
